spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DiplomaDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    cloud:
        gateway:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:8080"
                allowedHeaders: "*"
                allowedMethods: "*"
